// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLOwJ-mgZyM9ZDlmJIua14hPt_n6anfQ',
    appId: '1:1026033139455:web:4e728463e1b77f749356ca',
    messagingSenderId: '1026033139455',
    projectId: 'technicians-2d714',
    authDomain: 'technicians-2d714.firebaseapp.com',
    storageBucket: 'technicians-2d714.appspot.com',
    measurementId: 'G-HJ1PY4SKYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6fhIjt7vns3p9c61AZYvhhnfGq0XEmww',
    appId: '1:1026033139455:android:1d1b86a4ae02e43b9356ca',
    messagingSenderId: '1026033139455',
    projectId: 'technicians-2d714',
    storageBucket: 'technicians-2d714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4a5DsUVN0kdEmWBpt7PXwkYeQIkrH-0k',
    appId: '1:1026033139455:ios:e7b4f11c5d7187d39356ca',
    messagingSenderId: '1026033139455',
    projectId: 'technicians-2d714',
    storageBucket: 'technicians-2d714.appspot.com',
    iosClientId: '1026033139455-a16l7vdjjmc5vsjug6gnq2r6hdqsqo0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicians',
  );
}
